version: '3.8'

services:
  mongodb:
    volumes:
      - ./database/mongodb:/data/db

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-gateway/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống


  authenticate-service:
    build:
      context: ./services/authenticate-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/authenticate-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống

  comment-service:
    build:
      context: ./services/comment-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/comment-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống

  third-party-service:
    build:
      context: ./services/third-party-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/third-party-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống

  file-service:
    build:
      context: ./services/file-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/file-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống

  post-service:
    build:
      context: ./services/post-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/post-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/user-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống

  postreport-service:
    build:
      context: ./services/postreport-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/postreport-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./web-app:/app
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8080:8080"