version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-gateway/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống
    ports:
      - "3000:3000"

  authenticate-service:
    build:
      context: ./services/authenticate-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/authenticate-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống

    ports:
      - "3005:3005"

  comment-service:
    build:
      context: ./services/comment-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/comment-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống
    ports:
      - "3001:3001"

  file-service:
    build:
      context: ./services/file-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/file-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống
    ports:
      - "3003:3003"

  post-service:
    build:
      context: ./services/post-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/post-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống
    ports:
      - "3002:3002"

  reaction-service:
    build:
      context: ./services/reaction-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/reaction-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống
    ports:
      - "3004:3004"

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/user-service/src:/app/src
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống
    ports:
      - "3006:3006"

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./web-app:/app
      - /app/node_modules    # Ghi đè node_modules trong container bằng thư mục trống
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "8080:8080"