version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
      
  redis:
    image: redis:6
    container_name: redis
    networks:
      - app-network

  # RabbitMQ (nếu bạn dùng message-broker kiểu AMQP)
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - authenticate-service
      - comment-service
      - post-service
      - user-service
      - postreport-service
    networks:
      - app-network

  # Comment Service
  comment-service:
    build: ./services/comment-service
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/commentdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network
  
  # third-party service
  third-party-service:
    build: ./services/third-party-service
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/thirdpartydb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  # Post Service
  post-service:
    build: ./services/post-service
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/postdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  # File Service
  file-service:
    build: ./services/file-service
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/filedb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  # Authenticate Service
  authenticate-service:
    build: ./services/authenticate-service
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/authdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  # User Service
  user-service:
    build: ./services/user-service
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/userdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network
   
   # Post report Service
  postreport-service:
    build: ./services/postreport-service
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/postreportdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network
  # Web UI
  web-app:
    build: ./web-app
    ports:
      - "8080:8080"
    depends_on:
      - api-gateway
    networks:
      - app-network
      
volumes:
  mongo_data:

networks:
  app-network: